//! OTLP protobuf + gRPC client generated by `build.rs` (tonic + prost) from the
//! vendored legacy proto. See `proto/PROVENANCE.md` for source and why we pin
//! the old `InstrumentationLibraryMetrics` + deprecated `labels` shape.
//!
//! tonic emits one flat module per proto package; re-nest them so call sites
//! read like the upstream `opentelemetry.proto.*` package paths.
#![allow(clippy::all)]

pub mod opentelemetry {
    pub mod proto {
        pub mod common {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.common.v1");
            }
        }
        pub mod resource {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.resource.v1");
            }
        }
        pub mod metrics {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.metrics.v1");
            }
        }
        pub mod collector {
            pub mod metrics {
                pub mod v1 {
                    tonic::include_proto!("opentelemetry.proto.collector.metrics.v1");
                }
            }
        }
    }
}
