//! Blob storage + PDF extraction end-to-end. Run with:
//!   NO_PROXY='*' cargo test -p veda-server --test blob_extract_test -- --ignored --test-threads=1
//!
//! Requires real MySQL + Milvus + embedding (see config/test.toml).

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use serde::Deserialize;
use tokio::sync::watch;
use uuid::Uuid;
use veda_core::service::fs::FsService;
use veda_core::store::{AuthStore, MetadataStore, VectorStore};
use veda_pipeline::embedding::EmbeddingProvider;
use veda_pipeline::extraction::extract_text;
use veda_server::worker::Worker;
use veda_store::{MilvusStore, MysqlStore};
use veda_types::{SourceType, StorageType, Workspace, WorkspaceKind, WorkspaceStatus};

/// A real 1-page PDF (generated by cupsfilter) whose text layer contains the
/// sentinel "SALAMANDER_42". Used to prove the full pdf → extract → embed →
/// Milvus search path, and lossless blob round-trip.
const PDF_BYTES: &[u8] = include_bytes!("fixtures/veda_e2e.pdf");

/// Real .docx / .doc (textutil-generated) with sentinel "VEDA_WORD_SENTINEL_88"
/// and Chinese text — shared with veda-pipeline's extractor unit tests.
const DOCX_BYTES: &[u8] =
    include_bytes!("../../veda-pipeline/tests/fixtures/veda_word_e2e.docx");
const DOC_BYTES: &[u8] = include_bytes!("../../veda-pipeline/tests/fixtures/veda_word_e2e.doc");

#[derive(Debug, Deserialize)]
struct MysqlSection {
    database_url: String,
}
#[derive(Debug, Deserialize)]
struct MilvusSection {
    url: String,
    token: Option<String>,
    db: Option<String>,
}
#[derive(Debug, Deserialize)]
struct EmbeddingSection {
    api_url: String,
    api_key: String,
    model: String,
    dimension: u32,
    #[serde(default = "default_embed_batch")]
    batch_size: usize,
}
fn default_embed_batch() -> usize {
    10
}
#[derive(Debug, Deserialize)]
struct TestConfig {
    mysql: MysqlSection,
    milvus: MilvusSection,
    embedding: EmbeddingSection,
}

fn load_config() -> TestConfig {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .unwrap()
        .join("config/test.toml");
    let raw = std::fs::read_to_string(&path).expect("read config/test.toml");
    toml::from_str(&raw).expect("parse test.toml")
}

async fn make_workspace(mysql: &Arc<MysqlStore>) -> String {
    let ws = Uuid::new_v4().to_string();
    let now = chrono::Utc::now();
    mysql
        .create_workspace(&Workspace {
            id: ws.clone(),
            account_id: Uuid::new_v4().to_string(),
            name: format!("blob-{}", &ws[..8]),
            status: WorkspaceStatus::Active,
            kind: WorkspaceKind::Fs,
            app_id: None,
            description: None,
            created_at: now,
            updated_at: now,
        })
        .await
        .unwrap();
    ws
}

async fn cleanup(mysql: &MysqlStore, milvus: &MilvusStore, ws: &str, file_ids: &[String]) {
    for fid in file_ids {
        let _ = milvus.delete_chunks(ws, fid).await;
    }
    let pool = mysql.pool();
    let _ = sqlx::query(
        r#"DELETE fb FROM veda_file_blobs fb
           INNER JOIN veda_files f ON fb.file_id = f.id
           WHERE f.workspace_id = ?"#,
    )
    .bind(ws)
    .execute(pool)
    .await;
    let _ = sqlx::query(
        r#"DELETE fe FROM veda_file_extracts fe
           INNER JOIN veda_files f ON fe.file_id = f.id
           WHERE f.workspace_id = ?"#,
    )
    .bind(ws)
    .execute(pool)
    .await;
    let _ = sqlx::query(
        r#"DELETE fc FROM veda_file_chunks fc
           INNER JOIN veda_files f ON fc.file_id = f.id
           WHERE f.workspace_id = ?"#,
    )
    .bind(ws)
    .execute(pool)
    .await;
    let _ = sqlx::query("DELETE FROM veda_files WHERE workspace_id = ?")
        .bind(ws)
        .execute(pool)
        .await;
    let _ = sqlx::query("DELETE FROM veda_dentries WHERE workspace_id = ?")
        .bind(ws)
        .execute(pool)
        .await;
    let _ = sqlx::query("DELETE FROM veda_outbox WHERE workspace_id = ?")
        .bind(ws)
        .execute(pool)
        .await;
    let _ = sqlx::query("DELETE FROM veda_workspaces WHERE id = ?")
        .bind(ws)
        .execute(pool)
        .await;
}

/// PDF and arbitrary binary store as blobs and round-trip byte-for-byte, with
/// the right detected mime / source_type — exercises the real MySQL LONGBLOB
/// path (not the mock).
#[tokio::test]
#[ignore]
async fn blob_round_trips_losslessly_e2e() {
    let cfg = load_config();
    let mysql = Arc::new(MysqlStore::new(&cfg.mysql.database_url).await.unwrap());
    mysql.migrate().await.unwrap();
    let milvus = Arc::new(MilvusStore::new(
        &cfg.milvus.url,
        cfg.milvus.token.clone(),
        cfg.milvus.db.clone(),
    ));
    let fs = FsService::new(mysql.clone());
    let ws = make_workspace(&mysql).await;

    // PDF → stored as blob, detected as application/pdf / Pdf, bytes intact.
    let pdf = fs
        .write_blob(&ws, "/doc.pdf", PDF_BYTES.to_vec(), None)
        .await
        .unwrap();
    let (bytes, mime) = fs.read_file_raw(&ws, "/doc.pdf").await.unwrap();
    assert_eq!(bytes, PDF_BYTES, "PDF must round-trip losslessly");
    assert_eq!(mime, "application/pdf");
    let f = mysql.get_file(&pdf.file_id).await.unwrap().unwrap();
    assert_eq!(f.source_type, SourceType::Pdf);
    assert_eq!(f.storage_type, StorageType::Blob);

    // Arbitrary binary (NUL + high bytes) → Binary, bytes intact.
    let jar = b"PK\x03\x04\x00\x01\xff\xfe\0jar\0bytes\xc0here".to_vec();
    let jr = fs
        .write_blob(&ws, "/app.jar", jar.clone(), None)
        .await
        .unwrap();
    let (jb, _) = fs.read_file_raw(&ws, "/app.jar").await.unwrap();
    assert_eq!(jb, jar, "binary must round-trip losslessly");
    let jf = mysql.get_file(&jr.file_id).await.unwrap().unwrap();
    assert_eq!(jf.source_type, SourceType::Binary);

    cleanup(&mysql, &milvus, &ws, &[pdf.file_id, jr.file_id]).await;
}

/// A PDF's text layer is extracted, embedded, and searchable in Milvus —
/// the original PDF bytes stay downloadable while its content becomes
/// retrievable.
#[tokio::test]
#[ignore]
async fn pdf_extracts_and_becomes_searchable_e2e() {
    let cfg = load_config();

    // Sanity: the pure-Rust extractor recovers the text layer (sentinel word).
    let extracted = extract_text(PDF_BYTES, "application/pdf").unwrap();
    assert!(
        extracted.contains("SALAMANDER_42"),
        "extract_text must recover the PDF text layer; got: {:?}",
        &extracted[..extracted.len().min(300)]
    );

    let mysql = Arc::new(MysqlStore::new(&cfg.mysql.database_url).await.unwrap());
    mysql.migrate().await.unwrap();
    let milvus = Arc::new(MilvusStore::new(
        &cfg.milvus.url,
        cfg.milvus.token.clone(),
        cfg.milvus.db.clone(),
    ));
    milvus
        .init_collections(cfg.embedding.dimension)
        .await
        .unwrap();
    let embedding = Arc::new(
        EmbeddingProvider::new_tuned(
            &cfg.embedding.api_url,
            &cfg.embedding.api_key,
            &cfg.embedding.model,
            cfg.embedding.dimension,
            cfg.embedding.batch_size,
            8,
        )
        .unwrap(),
    );
    let fs = FsService::new(mysql.clone());
    let ws = make_workspace(&mysql).await;

    let pdf = fs
        .write_blob(&ws, "/doc.pdf", PDF_BYTES.to_vec(), None)
        .await
        .unwrap();

    // Run the worker until ExtractSync watermarks the file (or we time out).
    let worker = Worker::new(
        mysql.clone(),
        mysql.clone(),
        milvus.clone(),
        mysql.clone(),
        milvus.clone(),
        embedding.clone(),
        None,
        4,
        1,
        2048,
    );
    let (tx, rx) = watch::channel(false);
    let h = tokio::spawn(async move { worker.run(rx).await });
    let deadline = std::time::Instant::now() + Duration::from_secs(120);
    loop {
        tokio::time::sleep(Duration::from_secs(3)).await;
        let f = mysql.get_file(&pdf.file_id).await.unwrap().unwrap();
        if f.last_embedded_content_hash.is_some() || std::time::Instant::now() > deadline {
            break;
        }
    }
    let _ = tx.send(true);
    let _ = h.await;

    // The PDF's extracted text is now indexed in Milvus under its file_id.
    let file_ids = milvus.list_chunk_file_ids(&ws).await.unwrap();
    assert!(
        file_ids.contains(&pdf.file_id),
        "PDF must have chunks in Milvus after ExtractSync (extracted text indexed)"
    );

    // And the original PDF bytes are still byte-identical on read.
    let (bytes, mime) = fs.read_file_raw(&ws, "/doc.pdf").await.unwrap();
    assert_eq!(bytes, PDF_BYTES);
    assert_eq!(mime, "application/pdf");

    cleanup(&mysql, &milvus, &ws, &[pdf.file_id]).await;
}

/// Word documents (.docx + legacy .doc) run the full pipeline: upload →
/// ExtractSync extracts + stores full text + embeds into Milvus → the file is
/// searchable, its text readable via read_file/preview — and deleting it
/// leaves no extract row behind.
#[tokio::test]
#[ignore]
async fn word_extracts_readable_and_cleans_up_e2e() {
    let cfg = load_config();
    let mysql = Arc::new(MysqlStore::new(&cfg.mysql.database_url).await.unwrap());
    mysql.migrate().await.unwrap();
    let milvus = Arc::new(MilvusStore::new(
        &cfg.milvus.url,
        cfg.milvus.token.clone(),
        cfg.milvus.db.clone(),
    ));
    milvus
        .init_collections(cfg.embedding.dimension)
        .await
        .unwrap();
    let embedding = Arc::new(
        EmbeddingProvider::new_tuned(
            &cfg.embedding.api_url,
            &cfg.embedding.api_key,
            &cfg.embedding.model,
            cfg.embedding.dimension,
            cfg.embedding.batch_size,
            8,
        )
        .unwrap(),
    );
    let fs = FsService::new(mysql.clone());
    let ws = make_workspace(&mysql).await;

    let docx = fs
        .write_blob(&ws, "/w.docx", DOCX_BYTES.to_vec(), None)
        .await
        .unwrap();
    let doc = fs
        .write_blob(&ws, "/w.doc", DOC_BYTES.to_vec(), None)
        .await
        .unwrap();
    for (fid, want_src) in [(&docx.file_id, SourceType::Word), (&doc.file_id, SourceType::Word)] {
        let f = mysql.get_file(fid).await.unwrap().unwrap();
        assert_eq!(f.source_type, want_src);
        assert_eq!(f.storage_type, StorageType::Blob);
    }

    // Before the worker runs, the text read is a clear "pending" error.
    let err = fs.read_file(&ws, "/w.docx").await.unwrap_err();
    assert!(err.to_string().contains("提取"), "err: {err}");

    let worker = Worker::new(
        mysql.clone(),
        mysql.clone(),
        milvus.clone(),
        mysql.clone(),
        milvus.clone(),
        embedding.clone(),
        None,
        4,
        1,
        2048,
    );
    let (tx, rx) = watch::channel(false);
    let h = tokio::spawn(async move { worker.run(rx).await });
    let deadline = std::time::Instant::now() + Duration::from_secs(120);
    loop {
        tokio::time::sleep(Duration::from_secs(3)).await;
        let a = mysql.get_file(&docx.file_id).await.unwrap().unwrap();
        let b = mysql.get_file(&doc.file_id).await.unwrap().unwrap();
        if (a.last_embedded_content_hash.is_some() && b.last_embedded_content_hash.is_some())
            || std::time::Instant::now() > deadline
        {
            break;
        }
    }
    let _ = tx.send(true);
    let _ = h.await;

    // Both files' extracted text is indexed in Milvus…
    let file_ids = milvus.list_chunk_file_ids(&ws).await.unwrap();
    assert!(file_ids.contains(&docx.file_id), "docx chunks missing in Milvus");
    assert!(file_ids.contains(&doc.file_id), "doc chunks missing in Milvus");

    // …the stored extract serves read_file with sentinel + Chinese intact…
    for path in ["/w.docx", "/w.doc"] {
        let text = fs.read_file(&ws, path).await.unwrap();
        assert!(text.contains("VEDA_WORD_SENTINEL_88"), "{path}: {text:?}");
        assert!(text.contains("中文段落"), "{path}: {text:?}");
        let p = fs.read_file_preview(&ws, path, 64 * 1024).await.unwrap();
        assert!(!p.is_binary, "{path} preview must be text");
        assert!(p.content.contains("VEDA_WORD_SENTINEL_88"), "{path}");
    }

    // …and the original bytes still round-trip.
    let (bytes, _) = fs.read_file_raw(&ws, "/w.doc").await.unwrap();
    assert_eq!(bytes, DOC_BYTES);

    // Deleting the file removes its extract row in the same transaction —
    // no orphaned extracted text may survive.
    let count_extracts = |fid: String| {
        let pool = mysql.pool().clone();
        async move {
            let row: (i64,) =
                sqlx::query_as("SELECT COUNT(*) FROM veda_file_extracts WHERE file_id = ?")
                    .bind(&fid)
                    .fetch_one(&pool)
                    .await
                    .unwrap();
            row.0
        }
    };
    assert_eq!(count_extracts(docx.file_id.clone()).await, 1);
    fs.delete(&ws, "/w.docx").await.unwrap();
    assert_eq!(
        count_extracts(docx.file_id.clone()).await,
        0,
        "extract row must be deleted with the file"
    );

    cleanup(&mysql, &milvus, &ws, &[docx.file_id, doc.file_id]).await;
}
